set(STB_INCLUDE_PATH ${PROJECT_SOURCE_DIR}/external/stb CACHE FILEPATH "stb library directory" FORCE)
set(UUID_INCLUDE_PATH ${PROJECT_SOURCE_DIR}/external/stduuid CACHE FILEPATH "stduuiD interface directory" FORCE)
set(KTX_DIR ${PROJECT_SOURCE_DIR}/external/ktx CACHE FILEPATH "ktx directory" FORCE)

add_subdirectory(${PROJECT_SOURCE_DIR}/external/glfw)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/glm)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/tinyobjloader)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/tinygltf)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/imgui)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/spdlog)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/VulkanMemoryAllocator)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/assimp)