set(STB_INCLUDE_PATH ${PROJECT_SOURCE_DIR}/external/stb)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/glfw)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/glm)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/tinyobjloader)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/tinygltf)
include_directories(${PROJECT_SOURCE_DIR}/external/ktx/include)
#include_directories(${PROJECT_SOURCE_DIR}/external/ktx/other_include)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/imgui)
add_subdirectory(${PROJECT_SOURCE_DIR}/external/spdlog)
